main:
    server_name: "dell_ec"
    #options: "openbmc" | "dell_ec" | "mockup"

listen:
    - http::8080
    - https::8443
    - pprof::9080

session:
    timeout: 600

views:
  "testview":
      "Logger": ["module", "abc123"]
      "models":
        - "default":  {"property1": "value1"}
      "controllers":
      "view":
        - "with_URI": "/redfish/v1/testview#[foo]"
        - "with_foo": ""
        - "with_bar": ""
        - "with_aggregate": "name"

# TODO: certain attributes are inputs to if statements for the "actual" property, ie System.Chassis.1#ChassisPower.1#ChassisPowerStatus.1:
#     if(chassis_power_value == CHASSIS_STANDBY_POWER_STATE_EC)
#        ChassisObject[CHASSIS_POWERSTATE_KEY] = "Off";
#     else if(chassis_power_value == CHASSIS_POWER_ON_STATE_EC)
#        ChassisObject[CHASSIS_POWERSTATE_KEY] = "On";
#     else if(chassis_power_value == CHASSIS_POWERING_ON_STATE_EC)
#        ChassisObject[CHASSIS_POWERSTATE_KEY] = "PoweringOn";
#     else if(chassis_power_value == CHASSIS_POWERING_OFF_STATE_EC)
#        ChassisObject[CHASSIS_POWERSTATE_KEY] = "PoweringOff";
# move these attributes to awesome_mapper and add the if selection

awesome_mapper:
    fan:
        - { Select: "type == 'FanEvent' && data.ObjectHeader.FQDD == fqdd",
            ModelUpdate: [
                {Property: "fanpwm", Query: "data.Fanpwm" },
                {Property: "key", Query: "data.Key" },
                {Property: "fanname", Query: "data.FanName" },
                {Property: "Fanpwm_int", Query: "data.Fanpwm_int" },
                {Property: "VendorName", Query: "data.VendorName" },
                {Property: "WarningThreshold", Query: "data.WarningThreshold" },
                {Property: "DeviceName", Query: "data.DeviceName" },
                {Property: "TachName", Query: "data.TachName" },
                {Property: "CriticalThreshold", Query: "data.CriticalThreshold" },
                {Property: "Fanhealth", Query: "data.Fanhealth" },
                {Property: "Numrotors", Query: "data.Numrotors" },
                {Property: "Rotor2rpm", Query: "data.Rotor2rpm" },
                {Property: "Rotor1rpm", Query: "data.Rotor1rpm" },
                {Property: "rpm", Query: "(data.Rotor1rpm+data.Rotor2rpm)/2" },
                {Property: "FanStateMask", Query: "data.FanStateMask" }]}

    iom:
        - { Select: "type == 'AttributeUpdated' && data.FQDD == fqdd && data.Name == 'InstantaneousPower'", ModelUpdate: [ {Property: "Instantaneous_Power", Query: "data.Value", Default: 0} ] }

    power:
        - { Select: "type == 'AttributeUpdated' && data.FQDD == 'System.Chassis.1' && data.Group == 'SystemPwrMon' && data.Index == '1' && data.Name == 'AccumulativePower'", ModelUpdate: [ {Property: "Energy_Consumption_kWh", Query: "(data.Value)/1000", Default: 0 } ] }

    health:
        - { Select: "type == 'HealthEvent' && data.FQDD == fqdd", ModelUpdate: [ {Property: "health", Query: "data.Health" } ] }

    global_health:
        - { Select: "type == 'HealthEvent' && data.FQDD == 'System.Chassis.1#SubSystem.1#Fan'", ModelUpdate: [ {Property: "fan_rollup", Query: "data.Health" } ] }
        - { Select: "type == 'HealthEvent' && data.FQDD == 'System.Chassis.1#SubSystem.1#Temperature'", ModelUpdate: [ {Property: "temperature_rollup", Query: "data.Health" } ] }
        - { Select: "type == 'HealthEvent' && data.FQDD == 'System.Chassis.1#SubSystem.1#MM'", ModelUpdate: [ {Property: "mm_rollup", Query: "data.Health" } ] }
        - { Select: "type == 'HealthEvent' && data.FQDD == 'System.Chassis.1#SubSystem.1#SledSystem'", modelupdate: [ {Property: "sled_rollup", Query: "data.Health" } ] }
        - { Select: "type == 'HealthEvent' && data.FQDD == 'System.Chassis.1#SubSystem.1#PowerSupply'", ModelUpdate: [ {Property: "psu_rollup", Query: "data.Health" } ] }
        - { Select: "type == 'HealthEvent' && data.FQDD == 'System.Chassis.1#SubSystem.1#CMC'", ModelUpdate: [ {Property: "cmc_rollup", Query: "data.Health" } ] }
        - { Select: "type == 'HealthEvent' && data.FQDD == 'System.Chassis.1#SubSystem.1#Miscellaneous'", ModelUpdate: [ {Property: "misc_rollup", Query: "data.Health" } ] }
        - { Select: "type == 'HealthEvent' && data.FQDD == 'System.Chassis.1#SubSystem.1#Battery'", ModelUpdate: [ {Property: "battery_rollup", Query: "data.Health" } ] }
        - { Select: "type == 'HealthEvent' && data.FQDD == 'System.Chassis.1#SubSystem.1#IOMSubsystem'", ModelUpdate: [ {Property: "iom_rollup", Query: "data.Health" } ] }


mappings:
    test/testview:
        - {Property: "model",                    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Name" }

    Chassis/System.Modular:
        - {Property: "description",  FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Description" }
        - {Property: "service_tag",  FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "ServiceTag" }
        - {Property: "power_state",  FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "PowerState" }
        - {Property: "chassis_type", FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "ChassisType" }
        - {Property: "model",        FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Model" }
        - {Property: "manufacturer", FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Manufacturer" }
        - {Property: "serial",       FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "SerialNumber" }
        - {Property: "part_number",  FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "PartNumber" }
        - {Property: "name",         FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Name" }
        - {Property: "sled_profile", FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "SledProfile" }

    firmware/inventory:
        - {Property: "fw_device_class",     FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "DeviceClass" }
        - {Property: "fw_description",      FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "Description"}
        - {Property: "fw_device_context",   FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "DeviceContext" }
        - {Property: "fw_device_instance",  FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "DeviceInstance" }
        - {Property: "fw_fqdd",             FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "FQDD" }
        - {Property: "fw_name",             FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "Name" }
        - {Property: "fw_install_date",     FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "InstallDate" }
        - {Property: "fw_updateable",       FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "Updateable" }
        - {Property: "fw_version",          FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "Version" }
        - {Property: "fw_version_sequence", FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "VersionSequence" }

    fpga_inventory:
        - {Property: "device_class",     FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "DeviceClass" }
        - {Property: "description",      FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "Description"}
        - {Property: "device_context",   FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "DeviceContext" }
        - {Property: "device_instance",  FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "DeviceInstance" }
        - {Property: "fqdd",             FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "FQDD" }
        - {Property: "name",             FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "Name" }
        - {Property: "label",            FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "Label" }
        - {Property: "install_date",     FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "InstallDate" }
        - {Property: "updateable",       FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "Updateable" }
        - {Property: "version",          FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "Version" }
        - {Property: "version_sequence", FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "VersionSequence" }

    # map AR entries to back end model
    PSU/PSU.Slot:
        - {Property: "capacity_watts",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Capacity" }
        - {Property: "component_id",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "ComponentID" }
        - {Property: "eff_capacity",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "EffCapacity" }
        - {Property: "firmware_version",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "FirmwareVersion" }
        - {Property: "graphics_uri",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "GraphicsURI" }
        - {Property: "hardware_version",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "HardwareVersion" }
        - {Property: "input_voltage_type",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "InputVoltageType" }
        - {Property: "name",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Name" }
        - {Property: "part_number",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "PartNumber" }
        - {Property: "redundancy",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Redundancy" }
        - {Property: "serial_number",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "SerialNumber" }
        - {Property: "state",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "State" }
        - {Property: "state_str",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "StateStr" }
        - {Property: "psOn",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "psOn" }

        # looks like these are not in AR
        #- {Property: "line_input_voltage",  FQDD: "PSU.Slot.1", Group: "Info", Index: "1", Name: "TODO" }
        #- {Property: "input_current",       FQDD: "PSU.Slot.1", Group: "Info", Index: "1", Name: "TODO" }
        #
    Managers/CMC.Integrated:
        - {Property: "firmware_version",        FQDD: "{FQDD}", Group: "FWInventory", Index: "1", Name: "Version" }
        - {Property: "name",                    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Name" }
        - {Property: "description",             FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Description" }
        - {Property: "health_state",            FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "State" }
        - {Property: "asset_tag",               FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "AssetTag" } #not listed in attributes.txt
        - {Property: "sku",                     FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "SKU" } #not listed in attributes.txt
        - {Property: "serial",                  FQDD: "System.Chassis.1", Group: "Info", Index: "1", Name: "SerialNumber" }
        - {Property: "part_number",             FQDD: "System.Chassis.1", Group: "Info", Index: "1", Name: "PartNumber" }
        - {Property: "chassis_type",            FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "ChassisType" }
        - {Property: "model",                   FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Model" }
        - {Property: "manufacturer",            FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Manufacturer" }
        - {Property: "description",             FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Description" }
        - {Property: "indicator_led",           FQDD: "System.Chassis.1", Group: "Info", Index: "1", Name: "IndicatorLED" }
        - {Property: "redundancy_mode",         FQDD: "{FQDD}", Group: "Redundancy", Index: "1", Name: "Mode" }
        - {Property: "redundancy_health_state", FQDD: "{FQDD}", Group: "Redundancy", Index: "1", Name: "State" }
        - {Property: "redundancy_min",          FQDD: "{FQDD}", Group: "Redundancy", Index: "1", Name: "MinNumNeeded" }
        - {Property: "redundancy_max",          FQDD: "{FQDD}", Group: "Redundancy", Index: "1", Name: "MaxNumSupported" }

    Chassis/IOM.Slot:
        - {Property: "asset_tag",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "AssetTag" }
        - {Property: "description",  FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Description" }
        - {Property: "power_state",  FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "PowerState" }
        - {Property: "serial",       FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "SerialNumber" }
        - {Property: "part_number",  FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "PartNumber" }
        - {Property: "chassis_type", FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "ChassisType" }
        - {Property: "model",        FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Model" }
        - {Property: "name",         FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Name" }
        - {Property: "manufacturer", FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Manufacturer" }
        - {Property: "service_tag",  FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "ServiceTag" }
        - {Property: "indicator_led", FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "IndicatorLED"}

    Chassis/System.Chassis:
        - {Property: "asset_tag",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "AssetTag" }
        - {Property: "description",  FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Description" }
        - {Property: "power_state",  FQDD: "{FQDD}", Group: "ChassisPower", Index: "1", Name: "ChassisPowerStatus.1" }
        - {Property: "serial",       FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "SerialNumber" }
        - {Property: "part_number",  FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "PartNumber" }
        - {Property: "chassis_type", FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "ChassisType" }
        - {Property: "model",        FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Model" }
        - {Property: "name",         FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Name" }
        - {Property: "manufacturer", FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "Manufacturer" }
        - {Property: "service_tag",  FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "ServiceTag" }
        - {Property: "indicator_led", FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "IndicatorLED"}

    Chassis/Slots:
        - {Property: "slot_config", FQDD: "System.Chassis.1", Group: "{GROUP}", Index: "{INDEX}", Name: "Config" }
        - {Property: "slot_contains", FQDD: "System.Chassis.1", Group: "{GROUP}", Index: "{INDEX}", Name: "Contains" }
        - {Property: "slot_name", FQDD: "System.Chassis.1", Group: "{GROUP}", Index: "{INDEX}", Name: "Name" }
        - {Property: "slot_occupied", FQDD: "System.Chassis.1", Group: "{GROUP}", Index: "{INDEX}", Name: "Occupied" }
        - {Property: "slot_slotname", FQDD: "System.Chassis.1", Group: "{GROUP}", Index: "{INDEX}", Name: "SlotName" }

    Chassis/SlotConfigs:
        - {Property: "columns", FQDD: "{ANY}", Group: "{GROUP}", Index: "{INDEX}", Name: "Columns" }
        - {Property: "location", FQDD: "{ANY}", Group: "{GROUP}", Index: "{INDEX}", Name: "Location" }
        - {Property: "name", FQDD: "{ANY}", Group: "{GROUP}", Index: "{INDEX}", Name: "Name" }
        - {Property: "order", FQDD: "{ANY}", Group: "{GROUP}", Index: "{INDEX}", Name: "Order" }
        - {Property: "orientation", FQDD: "{ANY}", Group: "{GROUP}", Index: "{INDEX}", Name: "Orientation" }
        - {Property: "parentConfig", FQDD: "{ANY}", Group: "{GROUP}", Index: "{INDEX}", Name: "ParentConfig" }
        - {Property: "rows", FQDD: "{ANY}", Group: "{GROUP}", Index: "{INDEX}", Name: "Rows" }
        - {Property: "type", FQDD: "{ANY}", Group: "{GROUP}", Index: "{INDEX}", Name: "Type" }

    Chassis/System.Chassis/Power:
        - {Property: "capacity_watts", FQDD: "System.Chassis.1", Group: "ChassisPower", Index: "1", Name: "SystemInputMaxPowerCapacity" }
        - {Property: "energy_consumption_start_time", FQDD: "System.Chassis.1", Group: "SystemPwrMonn", Index: "1", Name: "AccumulativeStartEnergy"}
        - {Property: "min_peak_watts", FQDD:"System.Chassis.1", Group: "SystemPwrMon", Index: "1", Name: "MinPowerWatts" }
        - {Property: "min_peak_watts_time", FQDD:"System.Chassis.1", Group: "SystemPwrMon", Index: "1", Name: "MinPowerTimeStr" }
        - {Property: "max_peak_watts", FQDD:"Systme.Chassis.1", Group: "SystemPwrMon", Index: "1", Name: "PeakPowerWatts" }
        - {Property: "max_peak_watts_time", FQDD:"Systme.Chassis.1", Group: "SystemPwrMon", Index: "1", Name: "PeakPowerTimeStr" }
        - {Property: "limit_in_watts", FQDD: "System.Chassis.1", Group: "ChassisPower", Index: "1", Name: "PowerCapValue" }
        - {Property: "cumulative_power_time", FQDD: "System.Chassis.1", Group: "SystemPwrMon", Index: "1", Name: "CumulativePowerStartTimeStr" } 

    Chassis/System.Chassis/Thermal:
        # no mappings for now: placeholder

    PowerSupply/PSU.Slot:
        # no mappings for now: placeholder

    Fans/Fan.Slot:
        - {Property: "health",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "FanHealth" }
        - {Property: "firmware_version",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "FirmwareVersion" }
        - {Property: "hardware_version",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "HardwareVersion" }
        - {Property: "graphics_uri",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "GraphicsURI" }
        - {Property: "name",    FQDD: "{FQDD}", Group: "Info", Index: "1", Name: "FanName" }

    UpdateService:
        # no mappings for now: placeholder

    Registries:
        # placeholder

    Registries/BaseMessages:
        - {Property: "registry_name",  Value: "Base Message Registry File" }
        - {Property: "registry_type",  Value: "Base.1.3.8" }

    Registries/Messages:
        # placeholder

    Registries/ManagerAttributeRegistry:
        - {Property: "registry_type",  Value: 29 }
